### ISSUE TITLE
Profile David Salvidar

### ISSUE THREAD

**Issue by 18kimn** [antievictionmappingproject/worst-evictors-bay-area#3]

**Comment by grchrrs** [comment]
### Didn't find David Salvidar, but I did find David _Saldivar_ > do we have his name spelled incorrectly?
Saldivar:
- listed often with [CRE Property Management (Commercial Realty Experts)](https://www.facebook.com/CRE-Property-Mgt-484536678382844/) in San Francisco ([LinkedIn](https://www.linkedin.com/in/david-saldivar-241b49/), [BBB](https://www.bbb.org/us/ca/san-francisco/profile/property-management/cre-property-management-commercial-realty-experts-1116-62505), [Facebook](https://www.facebook.com/david.saldivar.7374))
- Works at a firm: [E. Robert Miller & Associates](https://www.erobertmiller.com/) in Burlingame, CA (SF area)
- [Real estate attorney, broker, and "prop management expert"](https://lawlink.com/profile/19215/david-saldivar)

**Comment by 18kimn** [comment]
Hm, good catch. @azadag's [analysis](https://antievictionmap.slack.com/files/UA31FMV0Q/F03V23FEPRQ/901_report_pt_ii_ownership.pdf?origin_team=T0CD6KQTH&origin_channel=C034VLPH5CJ) of the landlords had "David Salvidar" so I'll tag him here to see if he can clarify. Also @erinmcel may know
